# Generated by Django 5.1.5 on 2025-01-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
